# Generated by Django 4.1.7 on 2023-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='aprovado'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
    ]
