# Generated by Django 4.1.7 on 2023-12-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicasite', '0005_alter_banner_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
